"use client";

import { Plus, Trash2 } from "lucide-react";

import { FormSection } from "@/components/forms/RecordFormLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export type TransactionLineItem = { key: string; name: string; description: string; quantity: string; unit_price: string; discount_amount: string; tax_amount: string };
export type TransactionTotals = { subtotal: number; discount: number; tax: number; total: number };
type ItemField = keyof Omit<TransactionLineItem, "key">;
let itemCounter = 0;

export function createTransactionLineItem(prefix = "transaction"): TransactionLineItem { itemCounter += 1; return { key: `${prefix}-item-${itemCounter}`, name: "", description: "", quantity: "1", unit_price: "0", discount_amount: "0", tax_amount: "0" }; }
export function transactionAmount(value: string) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; }
export function transactionLineTotal(item: TransactionLineItem) { return Math.max(0, transactionAmount(item.quantity) * transactionAmount(item.unit_price) - transactionAmount(item.discount_amount) + transactionAmount(item.tax_amount)); }
export function calculateTransactionTotals(items: TransactionLineItem[]): TransactionTotals { return items.reduce((result, item) => { result.subtotal += transactionAmount(item.quantity) * transactionAmount(item.unit_price); result.discount += transactionAmount(item.discount_amount); result.tax += transactionAmount(item.tax_amount); result.total += transactionLineTotal(item); return result; }, { subtotal: 0, discount: 0, tax: 0, total: 0 }); }
export function areTransactionItemsValid(items: TransactionLineItem[]) { return items.length > 0 && items.every((item) => item.name.trim() && transactionAmount(item.quantity) > 0 && transactionAmount(item.unit_price) >= 0 && transactionAmount(item.discount_amount) >= 0 && transactionAmount(item.tax_amount) >= 0 && transactionAmount(item.discount_amount) <= transactionAmount(item.quantity) * transactionAmount(item.unit_price) + transactionAmount(item.tax_amount)); }
export function serializeTransactionItems(items: TransactionLineItem[]) { return items.map((item, index) => ({ name: item.name.trim(), description: item.description.trim() || null, quantity: item.quantity, unit_price: item.unit_price, discount_amount: item.discount_amount, tax_amount: item.tax_amount, sort_order: index })); }
export function formatTransactionMoney(value: number, currency: string) { try { return new Intl.NumberFormat(undefined, { style: "currency", currency: currency || "USD", maximumFractionDigits: 2 }).format(value); } catch { return `${currency || "USD"} ${value.toFixed(2)}`; } }

export function TransactionLineItemsEditor({ items, onChange, currency, error, idPrefix, itemLabel = "Item", showDescription = true, showAdjustments = true }: { items: TransactionLineItem[]; onChange: (items: TransactionLineItem[]) => void; currency: string; error?: string | null; idPrefix: string; itemLabel?: string; showDescription?: boolean; showAdjustments?: boolean }) {
  function updateItem(index: number, field: ItemField, value: string) { onChange(items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item)); }
  function addItem(focusField: ItemField = "name") { const nextIndex = items.length; onChange([...items, createTransactionLineItem(idPrefix)]); requestAnimationFrame(() => document.querySelector<HTMLInputElement>(`[data-${idPrefix}-row="${nextIndex}"][data-transaction-field="${focusField}"]`)?.focus()); }
  function handleKeyDown(event: React.KeyboardEvent<HTMLInputElement>, index: number, field: ItemField) { if (event.key !== "Enter") return; event.preventDefault(); if (index === items.length - 1) addItem(field); else document.querySelector<HTMLInputElement>(`[data-${idPrefix}-row="${index + 1}"][data-transaction-field="${field}"]`)?.focus(); }
  return <FormSection title="Line items" description="Press Enter in a cell to move to the same field on the next row; Enter on the last row adds another item."><div className="overflow-x-auto"><table className={`w-full ${showDescription && showAdjustments ? "min-w-[900px]" : "min-w-[620px]"} border-separate border-spacing-0`}><thead><tr className="text-left text-xs uppercase tracking-wide text-copy-muted"><th className="border-b border-line-default px-2 py-2">{itemLabel}</th>{showDescription ? <th className="border-b border-line-default px-2 py-2">Description</th> : null}<th className="w-24 border-b border-line-default px-2 py-2">Qty</th><th className="w-32 border-b border-line-default px-2 py-2">Unit price</th>{showAdjustments ? <><th className="w-28 border-b border-line-default px-2 py-2">Discount</th><th className="w-28 border-b border-line-default px-2 py-2">Tax</th></> : null}<th className="w-32 border-b border-line-default px-2 py-2 text-right">Total</th><th className="w-12 border-b border-line-default" /></tr></thead><tbody>{items.map((item, index) => <tr key={item.key}><ItemInput idPrefix={idPrefix} index={index} field="name" value={item.name} onChange={updateItem} onKeyDown={handleKeyDown} placeholder="Service or product" />{showDescription ? <ItemInput idPrefix={idPrefix} index={index} field="description" value={item.description} onChange={updateItem} onKeyDown={handleKeyDown} placeholder="Optional details" /> : null}<ItemInput idPrefix={idPrefix} index={index} field="quantity" value={item.quantity} onChange={updateItem} onKeyDown={handleKeyDown} type="number" /><ItemInput idPrefix={idPrefix} index={index} field="unit_price" value={item.unit_price} onChange={updateItem} onKeyDown={handleKeyDown} type="number" />{showAdjustments ? <><ItemInput idPrefix={idPrefix} index={index} field="discount_amount" value={item.discount_amount} onChange={updateItem} onKeyDown={handleKeyDown} type="number" /><ItemInput idPrefix={idPrefix} index={index} field="tax_amount" value={item.tax_amount} onChange={updateItem} onKeyDown={handleKeyDown} type="number" /></> : null}<td className="border-b border-line-subtle px-2 py-2 text-right text-sm font-medium tabular-nums text-copy-primary">{formatTransactionMoney(transactionLineTotal(item), currency)}</td><td className="border-b border-line-subtle px-1 py-2"><Button type="button" variant="ghost" size="icon" aria-label={`Remove ${item.name || `line ${index + 1}`}`} disabled={items.length === 1} onClick={() => onChange(items.filter((_, itemIndex) => itemIndex !== index))}><Trash2 /></Button></td></tr>)}</tbody></table></div>{error ? <p role="alert" className="mt-3 text-sm text-state-danger">{error}</p> : null}<Button type="button" variant="outline" className="mt-4" onClick={() => addItem()}><Plus />Add line item</Button></FormSection>;
}

function ItemInput({ idPrefix, index, field, value, onChange, onKeyDown, type = "text", placeholder }: { idPrefix: string; index: number; field: ItemField; value: string; onChange: (index: number, field: ItemField, value: string) => void; onKeyDown: (event: React.KeyboardEvent<HTMLInputElement>, index: number, field: ItemField) => void; type?: string; placeholder?: string }) { return <td className="border-b border-line-subtle px-1 py-2"><Input {...{ [`data-${idPrefix}-row`]: index }} data-transaction-field={field} type={type} min={type === "number" ? "0" : undefined} step={type === "number" ? "0.01" : undefined} value={value} placeholder={placeholder} onChange={(event) => onChange(index, field, event.target.value)} onKeyDown={(event) => onKeyDown(event, index, field)} aria-label={`${field.replaceAll("_", " ")} line ${index + 1}`} /></td>; }
