"use client";

import { Trash2, X } from "lucide-react";

import type { AutomationActionDefinition, AutomationActionField, AutomationCondition, AutomationConditionField, AutomationRulePreview, AutomationTriggerGroup, InspectorSelection, RuleDraft } from "./types";
import { buildAction, formatModuleLabel, OPERATOR_LABELS, valueAsString } from "./utils";
import { Button } from "@/components/ui/button";
import { Field, FieldDescription, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Pill } from "@/components/ui/Pill";
import { RequiredMark } from "@/components/ui/RequiredMark";
import { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectTrigger, SelectValue } from "@/components/ui/select";
import { SettingsSwitchRow } from "@/components/ui/SettingsSwitchRow";
import { Sheet, SheetClose, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetOverlay, SheetPortal, SheetTitle } from "@/components/ui/sheet";
import { Textarea } from "@/components/ui/textarea";

function ConditionValueField({ condition, field, onChange }: { condition: AutomationCondition; field?: AutomationConditionField | null; onChange: (patch: Partial<AutomationCondition>) => void }) {
  const hidesValue = ["is_empty", "is_not_empty", "changed"].includes(condition.operator);
  const usesList = condition.operator === "in" || condition.operator === "not_in";
  return <Field><FieldLabel>Value</FieldLabel>{hidesValue ? <div className="rounded-[var(--radius-control)] border border-line-default bg-surface-muted px-3 py-2 text-sm text-copy-muted">No value needed</div> : field?.field_type === "select" && field.options.length && !usesList ? <Select value={valueAsString(condition.value)} onValueChange={(value) => onChange({ value })}><SelectTrigger aria-label="Condition value"><SelectValue placeholder="Choose value" /></SelectTrigger><SelectContent>{field.options.map((option) => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select> : <Input aria-label="Condition value" type={field?.field_type === "number" ? "number" : field?.field_type === "date" ? "date" : "text"} value={usesList ? (condition.values ?? []).join(", ") : valueAsString(condition.value)} onChange={(event) => onChange(usesList ? { values: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) } : { value: event.target.value })} placeholder={usesList ? "Comma-separated values" : "Value"} />}</Field>;
}

function ActionValueField({ field, value, onChange }: { field: AutomationActionField; value: unknown; onChange: (value: unknown) => void }) {
  return <Field><FieldLabel>{field.label}{field.required ? <RequiredMark /> : null}</FieldLabel>{field.field_type === "select" ? <Select value={valueAsString(value)} onValueChange={onChange}><SelectTrigger aria-label={field.label}><SelectValue placeholder={field.placeholder ?? "Choose value"} /></SelectTrigger><SelectContent>{field.options.map((option) => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select> : field.field_type === "textarea" ? <Textarea aria-label={field.label} value={valueAsString(value)} onChange={(event) => onChange(event.target.value)} placeholder={field.placeholder ?? undefined} /> : <Input aria-label={field.label} type={field.field_type === "number" ? "number" : "text"} value={valueAsString(value)} onChange={(event) => onChange(field.field_type === "number" && event.target.value !== "" ? Number(event.target.value) : event.target.value)} placeholder={field.placeholder ?? undefined} />}{field.field_type === "actor_or_user_id" ? <FieldDescription>Use “actor” for the user who caused the event, or enter a tenant user ID.</FieldDescription> : null}{field.field_type === "payload_or_number" ? <FieldDescription>Leave blank to use the triggering record.</FieldDescription> : null}</Field>;
}

export function AutomationInspector({ open, onOpenChange, selection, draft, triggerGroups, selectedTriggerDescription, conditionFields, actionDefinitions, messages, preview, previewError, onDraftChange, onTriggerChange, onEnabledChange, onUpdateCondition, onRemoveCondition, onUpdateAction, onRemoveAction }: {
  open: boolean; onOpenChange: (open: boolean) => void; selection: InspectorSelection; draft: RuleDraft; triggerGroups: AutomationTriggerGroup[]; selectedTriggerDescription: string;
  conditionFields: Map<string, AutomationConditionField>; actionDefinitions: Map<string, AutomationActionDefinition>; messages: string[]; preview?: AutomationRulePreview; previewError: boolean;
  onDraftChange: (patch: Partial<RuleDraft>) => void; onTriggerChange: (trigger: string) => void; onEnabledChange: (enabled: boolean) => void;
  onUpdateCondition: (id: string, patch: Partial<AutomationCondition>) => void; onRemoveCondition: (id: string) => void; onUpdateAction: (id: string, patch: Record<string, unknown>) => void; onRemoveAction: (id: string) => void;
}) {
  const condition = selection.kind === "condition" ? draft.conditions.find((item) => item.id === selection.id) : undefined;
  const conditionField = condition ? conditionFields.get(condition.field) : undefined;
  const action = selection.kind === "action" ? draft.actions.find((item) => item.id === selection.id) : undefined;
  const actionDefinition = action ? actionDefinitions.get(action.type) : undefined;
  const title = selection.kind === "settings" ? "Rule settings" : selection.kind === "trigger" ? "Trigger" : selection.kind === "condition" ? "Condition" : selection.kind === "action" ? "Action" : "Validation and status";

  return <Sheet open={open} onOpenChange={onOpenChange}><SheetPortal><SheetOverlay className="fixed inset-0 z-40 bg-overlay" /><SheetContent side="right" className="z-50 flex h-full w-full max-w-[34rem] flex-col border-l border-line-default bg-surface-raised outline-none">
    <SheetHeader className="flex items-start justify-between gap-4 border-b border-line-subtle px-5 py-4"><div><SheetTitle className="text-lg font-semibold text-copy-primary">{title}</SheetTitle><SheetDescription className="mt-1 text-sm text-copy-muted">Changes remain local until the rule is saved.</SheetDescription></div><SheetClose asChild><Button type="button" variant="ghost" size="icon-sm" aria-label="Close automation inspector"><X /></Button></SheetClose></SheetHeader>
    <div className="min-h-0 flex-1 overflow-y-auto px-5 py-5">
      {selection.kind === "settings" ? <FieldGroup><Field><FieldLabel htmlFor="automation-rule-name">Name <RequiredMark /></FieldLabel><Input id="automation-rule-name" value={draft.name} onChange={(event) => onDraftChange({ name: event.target.value })} placeholder="Follow up on new leads" /></Field><Field><FieldLabel htmlFor="automation-rule-description">Description</FieldLabel><Textarea id="automation-rule-description" value={draft.description} onChange={(event) => onDraftChange({ description: event.target.value })} /></Field><SettingsSwitchRow id="automation-rule-enabled" label="Rule enabled" description="Enablement is allowed only after preview validation succeeds." checked={draft.enabled} onCheckedChange={onEnabledChange} /></FieldGroup>
      : selection.kind === "trigger" ? <FieldGroup><Field><FieldLabel>Trigger event</FieldLabel><Select value={draft.trigger_event || undefined} onValueChange={onTriggerChange}><SelectTrigger aria-label="Trigger event"><SelectValue placeholder="Choose trigger" /></SelectTrigger><SelectContent>{triggerGroups.map((group) => <SelectGroup key={group.module_key}><SelectLabel>{formatModuleLabel(group.module_key)}</SelectLabel>{group.triggers.map((trigger) => <SelectItem key={trigger.key} value={trigger.key}>{trigger.label}</SelectItem>)}</SelectGroup>)}</SelectContent></Select></Field><div className="rounded-[var(--radius-control)] border border-line-default bg-surface-muted p-3 text-sm text-copy-secondary">{selectedTriggerDescription}</div></FieldGroup>
      : selection.kind === "condition" && condition ? <FieldGroup><Field><FieldLabel>Match mode</FieldLabel><Select value={draft.condition_mode} onValueChange={(value) => onDraftChange({ condition_mode: value as "all" | "any" })}><SelectTrigger aria-label="Condition match"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All conditions</SelectItem><SelectItem value="any">Any condition</SelectItem></SelectContent></Select></Field><Field><FieldLabel>Field</FieldLabel><Select value={condition.field || undefined} onValueChange={(value) => { const field = conditionFields.get(value); onUpdateCondition(condition.id, { field: value, operator: field?.operators[0] ?? "equals", value: "", values: [] }); }}><SelectTrigger aria-label="Condition field"><SelectValue placeholder="Choose field" /></SelectTrigger><SelectContent>{[...conditionFields.values()].map((field) => <SelectItem key={field.key} value={field.key}>{field.label}</SelectItem>)}</SelectContent></Select></Field><Field><FieldLabel>Operator</FieldLabel><Select value={condition.operator} onValueChange={(operator) => onUpdateCondition(condition.id, { operator, value: "", values: [] })}><SelectTrigger aria-label="Condition operator"><SelectValue /></SelectTrigger><SelectContent>{(conditionField?.operators ?? ["equals"]).map((operator) => <SelectItem key={operator} value={operator}>{OPERATOR_LABELS[operator] ?? operator}</SelectItem>)}</SelectContent></Select></Field><ConditionValueField condition={condition} field={conditionField} onChange={(patch) => onUpdateCondition(condition.id, patch)} /><Button type="button" variant="dangerGhost" onClick={() => onRemoveCondition(condition.id)}><Trash2 />Remove condition</Button></FieldGroup>
      : selection.kind === "action" && action ? <FieldGroup><Field><FieldLabel>Action type</FieldLabel><Select value={action.type || undefined} onValueChange={(value) => { const replacement = buildAction(actionDefinitions.get(value)); onUpdateAction(action.id, { ...replacement, id: action.id }); }}><SelectTrigger aria-label="Action type"><SelectValue placeholder="Choose action" /></SelectTrigger><SelectContent>{[...actionDefinitions.values()].map((definition) => <SelectItem key={definition.key} value={definition.key}>{definition.label}</SelectItem>)}</SelectContent></Select>{actionDefinition ? <FieldDescription>{actionDefinition.description}</FieldDescription> : null}</Field>{actionDefinition?.fields.map((field) => <ActionValueField key={field.key} field={field} value={action[field.key]} onChange={(value) => onUpdateAction(action.id, { [field.key]: value })} />)}<Button type="button" variant="dangerGhost" onClick={() => onRemoveAction(action.id)}><Trash2 />Remove action</Button></FieldGroup>
      : <div className="grid gap-4">{messages.length ? <div className="rounded-[var(--radius-control)] border border-state-warning/30 bg-state-warning-muted p-3 text-sm text-copy-secondary"><p className="font-semibold text-copy-primary">Needs attention</p><ul className="mt-2 list-disc space-y-1 pl-5">{messages.map((message) => <li key={message}>{message}</li>)}</ul></div> : <div className="rounded-[var(--radius-control)] border border-state-success/30 bg-state-success-muted p-3 text-sm text-state-success">Builder fields look complete.</div>}{preview ? <div className="grid gap-3"><div className="flex flex-wrap gap-2"><Pill>{preview.can_enable ? "Ready to enable" : "Draft only"}</Pill><Pill>{preview.condition_count} conditions</Pill><Pill>{preview.action_count} actions</Pill></div>{preview.warnings.length ? <ul className="list-disc space-y-1 pl-5 text-sm text-state-warning">{preview.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul> : null}</div> : null}{previewError ? <p role="alert" className="text-sm text-state-danger">The draft could not be validated. No actions were run.</p> : null}<p className="text-sm text-copy-muted">Validation checks configuration only. It never executes actions.</p></div>}
    </div><SheetFooter className="flex justify-end border-t border-line-subtle bg-surface px-5 py-4"><SheetClose asChild><Button type="button">Done editing</Button></SheetClose></SheetFooter>
  </SheetContent></SheetPortal></Sheet>;
}
