#!/usr/bin/env bash
set -euo pipefail

# Layout-family contract generation (docs/crm-evolution/10-dx-ci-api-contracts.md, Phase 2).
#
#   ./scripts/generate-contracts.sh            regenerate the committed artifacts
#   ./scripts/generate-contracts.sh --check    fail on drift without writing anything
#
# Both modes derive everything from the running backend, so the two committed artifacts
# are reproducible rather than hand-maintained. --check is what CI runs; the no-argument
# form is the documented repair command.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

MODE="write"
case "${1:-}" in
  "") ;;
  --check) MODE="check" ;;
  *)
    echo "usage: $0 [--check]" >&2
    exit 2
    ;;
esac

SPEC_PATH="frontend/contracts/record-layouts.openapi.json"
TYPES_PATH="frontend/contracts/generated/record-layouts.ts"
CONTAINER_SPEC_PATH="/app/contracts/record-layouts.openapi.json"
REPAIR_COMMAND="./scripts/generate-contracts.sh"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

TYPES_HEADER="/**
 * Generated by ${REPAIR_COMMAND} from ${SPEC_PATH}.
 * Do not edit by hand. Import domain types from \"@/lib/contracts/recordLayouts\" instead.
 */"

report_missing() {
  echo >&2
  echo "Missing generated contract artifact: $1" >&2
  echo "Repair with: ${REPAIR_COMMAND}" >&2
  exit 1
}

report_drift() {
  echo >&2
  echo "Contract drift detected in $1" >&2
  echo "The committed artifact no longer matches the backend contract shown in the diff above." >&2
  echo "Repair with: ${REPAIR_COMMAND}" >&2
  echo "Then review and commit the regenerated artifacts." >&2
  exit 1
}

compare_or_write() {
  local committed="$1"
  local fresh="$2"
  if [ "$MODE" = "check" ]; then
    [ -f "$committed" ] || report_missing "$committed"
    diff -u "$committed" "$fresh" || report_drift "$committed"
  else
    mkdir -p "$(dirname "$committed")"
    cp "$fresh" "$committed"
    echo "Wrote ${committed}"
  fi
}

echo "== Record-layout OpenAPI slice =="
docker compose exec -T backend python -m scripts.export_layout_contract \
  > "$TMP_DIR/record-layouts.openapi.json"
compare_or_write "$SPEC_PATH" "$TMP_DIR/record-layouts.openapi.json"

echo
echo "== Record-layout TypeScript contract =="
if ! docker compose exec -T frontend npx --no-install openapi-typescript --version >/dev/null 2>&1; then
  echo "openapi-typescript is not available in the frontend container." >&2
  echo "Repair with: docker compose exec -T frontend npm install" >&2
  exit 1
fi

# The generator reads the spec from inside the frontend container. In --check mode that
# copy has already been proven identical to the freshly exported backend contract above,
# so the TypeScript comparison below is a genuine end-to-end drift check.
docker compose exec -T frontend npx --no-install openapi-typescript "$CONTAINER_SPEC_PATH" \
  > "$TMP_DIR/openapi-typescript.ts"
{
  printf '%s\n' "$TYPES_HEADER"
  cat "$TMP_DIR/openapi-typescript.ts"
} > "$TMP_DIR/record-layouts.ts"
compare_or_write "$TYPES_PATH" "$TMP_DIR/record-layouts.ts"

echo
if [ "$MODE" = "check" ]; then
  echo "Generated contracts are up to date."
else
  echo "Generated contracts refreshed. Review the diff before committing."
fi
